import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';

interface NotificationState {
  isSupported: boolean;
  permission: NotificationPermission | null;
  isRegistered: boolean;
}

/**
 * Custom hook for managing browser notifications and service worker registration
 * 
 * Note: This is a scaffold. Full implementation requires:
 * - VAPID keys for push notifications
 * - Backend endpoint to store push subscriptions
 * - Service worker file (sw.js) for handling push events
 */
export function useNotifications() {
  const [state, setState] = useState<NotificationState>({
    isSupported: false,
    permission: null,
    isRegistered: false,
  });

  useEffect(() => {
    // Check if service worker and notifications are supported
    const isSupported = 'serviceWorker' in navigator && 'Notification' in window;
    
    if (isSupported) {
      // Check current notification permission
      const permission = Notification.permission;
      
      // Check if service worker is already registered
      navigator.serviceWorker.getRegistration().then((registration) => {
        setState({
          isSupported: true,
          permission,
          isRegistered: !!registration,
        });
      });
    } else {
      setState({
        isSupported: false,
        permission: null,
        isRegistered: false,
      });
    }
  }, []);

  /**
   * Request notification permission from the user
   */
  const requestPermission = async (): Promise<NotificationPermission> => {
    if (!state.isSupported) {
      throw new Error('Notifications are not supported in this browser');
    }

    const permission = await Notification.requestPermission();
    
    setState((prev) => ({
      ...prev,
      permission,
    }));

    return permission;
  };

  /**
   * Register the service worker
   * Note: The service worker file (sw.js) should be generated by next-pwa
   * during the build process
   */
  const registerServiceWorker = async (): Promise<ServiceWorkerRegistration | null> => {
    if (!state.isSupported) {
      throw new Error('Service workers are not supported in this browser');
    }

    try {
      // Wait for the service worker to be ready
      if ('serviceWorker' in navigator) {
        const registration = await navigator.serviceWorker.ready;
        
        setState((prev) => ({
          ...prev,
          isRegistered: true,
        }));

        return registration;
      }
    } catch (error) {
      console.error('Service worker registration failed:', error);
      throw error;
    }

    return null;
  };

  /**
   * Subscribe to push notifications
   */
  const subscribeToPush = async (): Promise<PushSubscription | null> => {
    if (!state.isSupported || state.permission !== 'granted') {
      throw new Error('Notifications are not supported or permission not granted');
    }

    try {
      const registration = await navigator.serviceWorker.ready;
      
      // Get VAPID public key from environment
      const vapidPublicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
      
      if (!vapidPublicKey) {
        console.warn('VAPID public key not found. Push notifications will not work.');
        return null;
      }

      // Convert VAPID key to Uint8Array
      const urlBase64ToUint8Array = (base64String: string) => {
        const padding = '='.repeat((4 - base64String.length % 4) % 4);
        const base64 = (base64String + padding)
          .replace(/\-/g, '+')
          .replace(/_/g, '/');
        const rawData = window.atob(base64);
        const outputArray = new Uint8Array(rawData.length);
        for (let i = 0; i < rawData.length; ++i) {
          outputArray[i] = rawData.charCodeAt(i);
        }
        return outputArray;
      };

      const applicationServerKey = urlBase64ToUint8Array(vapidPublicKey);
      
      // Subscribe to push notifications
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: applicationServerKey,
      });
      
      // Get auth token and send subscription to backend
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        throw new Error('Not authenticated');
      }

      const response = await fetch('/api/push/subscribe', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`,
        },
        body: JSON.stringify(subscription),
      });

      if (!response.ok) {
        throw new Error('Failed to save subscription');
      }
      
      return subscription;
    } catch (error) {
      console.error('Push subscription failed:', error);
      throw error;
    }
  };

  /**
   * Send a local notification (for testing)
   */
  const sendLocalNotification = (title: string, options?: NotificationOptions) => {
    if (!state.isSupported || state.permission !== 'granted') {
      throw new Error('Notifications are not supported or permission not granted');
    }

    new Notification(title, {
      body: options?.body,
      icon: options?.icon,
      badge: options?.badge,
      tag: options?.tag,
      requireInteraction: options?.requireInteraction,
    });
  };

  return {
    ...state,
    requestPermission,
    registerServiceWorker,
    subscribeToPush,
    sendLocalNotification,
  };
}


